# Generated by Django 3.1.4 on 2021-01-06 18:05

import datetime
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('password_date', models.DateField(default=datetime.date(2018, 10, 19))),
                ('entries', models.IntegerField(default=0)),
                ('timeout', models.DateTimeField(null=True)),
                ('password_history', models.TextField()),
            ],
        ),
    ]
