# Generated by Django 3.0.5 on 2020-11-29 20:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('password_date', models.DateField(default=datetime.date(2018, 10, 19))),
                ('entries', models.IntegerField(default=0)),
                ('timeout', models.DateTimeField(null=True)),
            ],
        ),
    ]
