<<<<<<< HEAD
# Generated by Django 3.1.3 on 2021-01-05 13:12

import datetime
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
=======
# Generated by Django 3.0.5 on 2020-11-29 20:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
>>>>>>> refs/remotes/origin/master


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('auth', '0012_alter_user_first_name_max_length'),
=======
        ('auth', '0011_update_proxy_permissions'),
>>>>>>> refs/remotes/origin/master
    ]

    operations = [
        migrations.CreateModel(
            name='NewUser',
            fields=[
<<<<<<< HEAD
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
=======
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
>>>>>>> refs/remotes/origin/master
                ('password_date', models.DateField(default=datetime.date(2018, 10, 19))),
                ('entries', models.IntegerField(default=0)),
                ('timeout', models.DateTimeField(null=True)),
            ],
        ),
    ]
