# Generated by Django 3.1.4 on 2021-01-18 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='is_worker',
            field=models.BooleanField(default=False),
        ),
    ]
