# Generated by Django 3.1.4 on 2021-01-19 19:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_newuser_is_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='pass_change_entries',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newuser',
            name='pass_timeout',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='password_date',
            field=models.DateField(default=datetime.date(2021, 1, 19)),
        ),
    ]
