# Generated by Django 3.1.4 on 2021-01-10 16:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_modules', '0002_allactions_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allactions',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 1, 10, 17, 49, 2, 911992)),
        ),
    ]
