# Generated by Django 3.1.4 on 2021-01-18 17:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_modules', '0004_auto_20210111_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allactions',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 1, 18, 18, 20, 24, 684898)),
        ),
    ]
