# Generated by Django 3.1.4 on 2021-01-18 17:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_modules', '0005_auto_20210118_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allactions',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 1, 18, 18, 52, 34, 147420)),
        ),
    ]
