# Generated by Django 3.1.4 on 2021-01-18 20:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_modules', '0006_auto_20210118_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allactions',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 1, 18, 21, 25, 10, 891951)),
        ),
    ]
