# Generated by Django 3.1.4 on 2021-01-19 19:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_modules', '0007_auto_20210118_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allactions',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 1, 19, 20, 23, 57, 475524)),
        ),
    ]
