# Generated by Django 3.0.5 on 2020-12-07 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(max_length=20)),
                ('nazwa', models.CharField(max_length=50)),
                ('cena', models.FloatField()),
                ('czas_przygotowania', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Skladnik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=20)),
                ('cena', models.FloatField()),
                ('typ', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Stolik_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stolik_miejsca', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rezerwacja_dzien', models.DateField()),
                ('begin_h', models.CharField(max_length=10)),
                ('begin_m', models.CharField(max_length=10)),
                ('end_h', models.CharField(max_length=10)),
                ('end_m', models.CharField(max_length=10)),
                ('czas_rezerwacji', models.DateTimeField(auto_now_add=True)),
                ('komentarz', models.TextField()),
                ('aktywnosc', models.BooleanField(default=True)),
                ('nazwa', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('stolik', models.ManyToManyField(default=None, to='reservation.Stolik_item')),
                ('zamowienie_item', models.ManyToManyField(default=None, to='reservation.Menu_item')),
            ],
        ),
        migrations.CreateModel(
            name='Menu_org',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zawartosc', models.ManyToManyField(default=None, to='reservation.Menu_item')),
            ],
        ),
        migrations.AddField(
            model_name='menu_item',
            name='skladniki',
            field=models.ManyToManyField(default=None, to='reservation.Skladnik'),
        ),
    ]
