<<<<<<< HEAD
# Generated by Django 3.1.3 on 2021-01-05 13:12

from django.conf import settings
import django.core.validators
=======
# Generated by Django 3.0.5 on 2020-12-07 14:27

from django.conf import settings
>>>>>>> refs/remotes/origin/master
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(max_length=20)),
                ('nazwa', models.CharField(max_length=50)),
<<<<<<< HEAD
                ('cena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('czas_przygotowania', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(120.0)])),
                ('zdjecie', models.ImageField(blank=True, default='default.jpg', upload_to='gallery')),
=======
                ('cena', models.FloatField()),
                ('czas_przygotowania', models.FloatField()),
>>>>>>> refs/remotes/origin/master
            ],
        ),
        migrations.CreateModel(
            name='Skladnik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=20)),
<<<<<<< HEAD
                ('cena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('typ', models.CharField(max_length=20)),
                ('zdjecie', models.ImageField(blank=True, default='default.jpg', upload_to='gallery')),
=======
                ('cena', models.FloatField()),
                ('typ', models.CharField(max_length=20)),
>>>>>>> refs/remotes/origin/master
            ],
        ),
        migrations.CreateModel(
            name='Stolik_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('stolik_miejsca', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(16)])),
                ('zdjecie', models.ImageField(blank=True, default='default.jpg', upload_to='gallery')),
=======
                ('stolik_miejsca', models.IntegerField()),
>>>>>>> refs/remotes/origin/master
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('cena_rachunek', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rezerwacja_dzien', models.DateField()),
                ('begin_h', models.IntegerField()),
                ('begin_m', models.IntegerField()),
                ('end_h', models.IntegerField()),
                ('end_m', models.IntegerField()),
                ('czas_rezerwacji', models.DateTimeField(auto_now_add=True)),
                ('modyfikacje', models.TextField(blank=True)),
                ('komentarz', models.TextField(blank=True)),
=======
                ('rezerwacja_dzien', models.DateField()),
                ('begin_h', models.CharField(max_length=10)),
                ('begin_m', models.CharField(max_length=10)),
                ('end_h', models.CharField(max_length=10)),
                ('end_m', models.CharField(max_length=10)),
                ('czas_rezerwacji', models.DateTimeField(auto_now_add=True)),
                ('komentarz', models.TextField()),
>>>>>>> refs/remotes/origin/master
                ('aktywnosc', models.BooleanField(default=True)),
                ('nazwa', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('stolik', models.ManyToManyField(default=None, to='reservation.Stolik_item')),
                ('zamowienie_item', models.ManyToManyField(default=None, to='reservation.Menu_item')),
            ],
        ),
        migrations.CreateModel(
            name='Menu_org',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('typ', models.CharField(max_length=20)),
=======
>>>>>>> refs/remotes/origin/master
                ('zawartosc', models.ManyToManyField(default=None, to='reservation.Menu_item')),
            ],
        ),
        migrations.AddField(
            model_name='menu_item',
            name='skladniki',
<<<<<<< HEAD
            field=models.ManyToManyField(blank=True, default=None, to='reservation.Skladnik'),
=======
            field=models.ManyToManyField(default=None, to='reservation.Skladnik'),
>>>>>>> refs/remotes/origin/master
        ),
    ]
