# Generated by Django 3.1.4 on 2021-01-20 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temp_reservation',
            name='aktywnosc',
        ),
        migrations.RemoveField(
            model_name='temp_reservation',
            name='cena_rachunek',
        ),
        migrations.RemoveField(
            model_name='temp_reservation',
            name='komentarz',
        ),
        migrations.RemoveField(
            model_name='temp_reservation',
            name='modyfikacje',
        ),
        migrations.RemoveField(
            model_name='temp_reservation',
            name='zamowienie_item',
        ),
    ]
