# Generated by Django 3.1.4 on 2021-01-22 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservation', '0002_auto_20210120_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produkt_rezerwacji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('podanie_godzina', models.IntegerField(blank=True, default=0)),
                ('podanie_minuta', models.IntegerField(blank=True, default=0)),
                ('dodaj_skladnik', models.ManyToManyField(blank=True, default=None, related_name='odejmij_skladnik', to='reservation.Skladnik')),
                ('nazwa_produktu', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='reservation.menu_item')),
                ('odejmij_skladnik', models.ManyToManyField(blank=True, default=None, related_name='dodaj_skladnik', to='reservation.Skladnik')),
            ],
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='modyfikacje',
        ),
        migrations.CreateModel(
            name='Tymczasowe_zamowienie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_uzytkownika', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tymczasowe_edytowane', models.ManyToManyField(blank=True, default=None, related_name='nazwa_uzytkownika', to='reservation.Produkt_rezerwacji')),
                ('zamowienie_item', models.ManyToManyField(default=None, to='reservation.Produkt_rezerwacji')),
            ],
        ),
        migrations.AlterField(
            model_name='reservation',
            name='zamowienie_item',
            field=models.ManyToManyField(blank=True, default=None, to='reservation.Produkt_rezerwacji'),
        ),
    ]
